version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: navihire
      POSTGRES_PASSWORD: navihire123
      POSTGRES_DB: navihire_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgresql://navihire:navihire123@postgres:5432/navihire_db
      - DATABASE_URL=postgresql://postgres:1827@localhost:5432/navihire_db

      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
